baseURL = 'https://citadin.cc'
languageCode = 'en-us'
title = "Citadin's well of endless knowledge"
theme = "typo"

[params]
  description="Your hub of knowledge"
  favicon="favicon.ico"
  theme="auto"
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'
  paginationSize = 13
  listDateFormat = '2 Jan 2006'

[markup]
  [markup.highlight]
  style = 'algol'
