baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "Citadin's well of endless knowledge"
theme = "nostyleplease"

[params]
  [params.theme_config]
    appearance        = "light"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = false
